use_frameworks!

target 'BeappLogger_Example' do
  pod 'BeappLogger', :path => '../'
  pod 'BeappLogger/Crashlytics', :path => '../'

  target 'BeappLogger_Tests' do
    inherit! :search_paths

    
  end
end
